name: Run test

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: yarn
      - name: yarn install
        run: yarn
      - name: install browsers
        run: yarn playwright install
      - name: Run backstop test
        run: yarn backstop test --config=content-migration.js || true
      - name: Run tar for backstop report
        if: always()
        run: tar -czvf backstop_report.tar.gz backstop_data/
      - name: Playwright report upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backstop_report.tar.gz
          path: backstop_report.tar.gz
